trigger:
  - main

stages:
  - stage: Development
    jobs:
      - deployment: Dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'EcomAzureConnection'
                    appName: 'ecom-backend-dev'
                    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
                    startUpCommand: 'npm start'

  - stage: Production
    condition: succeeded('Development')
    jobs:
      - deployment: Prod
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'EcomAzureConnection'
                    appName: 'ecom-backend-prod'
                    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
                    startUpCommand: 'npm start'