const { BlobServiceClient } = require("@azure/storage-blob");

module.exports = async function saveToStorageAccount(file, containerName) {
    try {
        const blobServiceClient = BlobServiceClient.fromConnectionString(
            process.env.AZURE_STORAGE_CONNECTION_STRING
        );

        // get container client (creates container if it doesn't exist)
        const containerClient = blobServiceClient.getContainerClient(containerName);
        await containerClient.createIfNotExists({
            access: 'container'
        });

        // Use the filename generated by multer
        const blobClient = containerClient.getBlockBlobClient(file.filename);

        // read the file from disk and upload it
        const fs = require('fs');
        const fileBuffer = fs.readFileSync(file.path);

        // upload file
        await blobClient.uploadData(fileBuffer, {
            blobHTTPHeaders: {
                blobContentType: file.mimetype
            }
        });

        // delete the local file after upload
        fs.unlinkSync(file.path);

        return blobClient.url;
    } catch (error) {
        console.error('Detailed Azure error:', error.message);
        throw new Error(`Failed to upload file to Azure: ${error.message}`);
    }
}